### ISSUE TITLE
Vertical pipe ( | ) looks weird in Fira Mono

### ISSUE THREAD

**Issue by sid-kap** [mozilla/Fira#102]
Hi,

When I try to use the vertical pipe symbol ( | ) in the latest Google Fonts version of Fira Mono, I see a diamond shape.

Is this intentional?

**Comment by patrykdesign** [comment]
@sid-kap no there seems to be an error. Can you attach a screenshot?
@davelab6 do you have an idea of what could be happening? Sounds like a missing or corrupt glyph.

**Comment by sid-kap** [comment]
![screen shot 2015-07-30 at 11 42 17 am](https://cloud.githubusercontent.com/assets/6425077/8991857/1b053e24-36b0-11e5-857e-e27288ab8908.png)

taken from https://www.google.com/fonts

**Comment by patrykdesign** [comment]
@sid-kap I just tried it out on a Mac both on Firefox and Chrome. I couldn't replicate the diamond.
![screen shot 2015-07-30 at 2 47 36 pm](https://cloud.githubusercontent.com/assets/1503049/8991983/fe1a5028-36c9-11e5-91de-a4b593b27082.png)

**Comment by jfkthame** [comment]
Are you sure you don't have an old version installed locally? I think the CSS used by Google Fonts will usually use a local copy if available, so in that case you may not be seeing the up-to-date font.

**Comment by sid-kap** [comment]
Yup, it was a problem with my local copy. I disabled my local copy in OS X's Font Book, and the fonts look correct now on the web. 

Thanks for your help!
