### ISSUE TITLE
Wrong acute position above some Cyrillic letters

### ISSUE THREAD

**Issue by shoorick** [mozilla/Fira#107]
Acutes above Cyrillic letters Ю (Yu, U+042E, U+044E) and Я (Ya, U+042F, U+044F) placed incorrectly. Acutes should be moved to left and upper for capital letters.

It is distincltly even in large font sizes:

![fira-acute](https://cloud.githubusercontent.com/assets/190892/9220033/e21c29ee-40f8-11e5-8ff9-4d2b53cb3213.png)

In small font sizes acute moves to next letter:

![fira-acute-small](https://cloud.githubusercontent.com/assets/190892/9220224/5666990a-40fa-11e5-87c1-a589450aeaf4.png)

P. S. First screenshot grabbed from Inkscape, second one grabbed from Google Chrome.  
See also [sample of text with acutes](http://ilmeny.org/doc/2015/prfinal) — it contains words **Митя́ев** (Fira Sans Bold) and **Батю́кина** (Fira Sans Regular).

**Comment by jfkthame** [comment]
@carrois It looks like those glyphs must lack the necessary attachment points (or they're missing from the coverage of the mark-to-base positioning lookup). It'd be good to verify that these attachments are present for the complete set of letters.

**Comment by schriftgestalt** [comment]
How often are the acutes used on Ю and Я?

**Comment by shoorick** [comment]
It depends from text. Usual texts which written for adult readers often contains no acutes at all.

But any _special_ text in Russian can have acute with any vowel: АЕИОУЫЭЮЯаеиоуыэюя. Ёё (Yo) often used without acute because this letter is stressed already (with few exclusion). Special texts are:
- literature for children who begins to read.
- dictionaries and encyclopedies (Wikipedia and Wiktionary too — see articles w:[Яблоко] (https://ru.wikipedia.org/wiki/%D0%AF%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE) and wt:[юность](https://ru.wiktionary.org/wiki/%D1%8E%D0%BD%D0%BE%D1%81%D1%82%D1%8C)).
- educational books with words which are unknown to reader.
- press releases; radio and TV staff asks to set acutes in releases.

**Comment by jfkthame** [comment]
In any case, regardless of whether they are commonly used or not, **all** base letters should have the attachment points necessary to position **any** diacritic above (or below) in a consistent manner. We can't predict exactly what unusual combinations someone might decide to write.

**Comment by schriftgestalt** [comment]
The user is free to add any anchors he thinks are needed. I only ask if I should add them to the default list. I try to only add them if there might have a regular use. Otherwise it would only clutter the files and increase the file size with unneeded mark attachments.

**Comment by carrois** [comment]
For Fira, we (user) will add top and bottom anchors to all base letters as Jonathan suggests with the next version.
Regardless of that, implementing top anchors as default would make sense to the Cyrillic vowels as shoorick pointed out quite a lot of use cases.

**Comment by patrykdesign** [comment]
Fixed with latest commit - Fira 4.106
