### ISSUE TITLE
Fira Sans Two, Four and Eight appears too light on Arch Linux

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/Fira#108]
![fira-sans-two-arch-linux](https://cloud.githubusercontent.com/assets/51007/9480273/5a6af398-4bd6-11e5-9d29-a01cfe86d001.png)

Found via subreddit [r/mozilla](https://www.reddit.com/r/mozilla/comments/3hxl0r/problem_with_mozillas_fira_sans/)

> I've been trying out Fira fonts on my desktop and laptop and they look great, apart from some headings on many built-in pages and sites where fonts Fira Sans Two, Four and Eight are used.
>
> [Screenshot of the terrible rendering](https://cloud.githubusercontent.com/assets/51007/9480273/5a6af398-4bd6-11e5-9d29-a01cfe86d001.png). This occurs inside and outside of Firefox. I have tried different font configuration combinations as well as the Infinality patch set. Is this a problem with the font itself?
>
> I'm using Arch Linux FWIW.

I’m guessing that this is an issue with the `freetype2` package and should be filed with them. But it’s possible that it’s an issue with our font instead, so I filed this bug just in case.

**Comment by patrykdesign** [comment]
Technically these sizes are more of a "BETA" so they are meant to be used on "at your own risk". They were more an exercise in extreme weights. But you're right they could have something to do with freetype2.
