### ISSUE TITLE
Keep clean file history

### ISSUE THREAD

**Issue by moyogo** [mozilla/Fira#116]
The source files in the ufo folder have the same name since  3.1.11 e9394392499545175eda283a894a412fa7456763 but the glyphs files keep getting deleted and replaced by files with different names without preserving history: 

For example in 01f5dc059cde9706d2ae0f295ca90736eb238ea3 the files source/glyph/FiraMono_3-2_SOURCE_150625.glyphs and source/glyphs/FiraMono_3-2_150908.glyphs should have been the same file in history but are two separate files instead, making the diffs unnecessarily large.

Either name the glyph source files without a date and version in the name, like source/glyph/FiraMono.glyphs, or do `git mv` if you need to change the file names.

**Comment by patrykdesign** [comment]
@moyogo makes sense, just removed the version and date, so the next update will start having cleaner versioning.

**Comment by moyogo** [comment]
Thanks
