### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by moyogo** [mozilla/Fira#117]
There should be tagged releases: https://github.com/mozilla/Fira/releases
Currently one has to browse through commits to see previous releases.

See https://help.github.com/articles/creating-releases/

**Comment by patrykdesign** [comment]
@moyogo thanks, I thought I was doing this in the terminal, but clearly not. Just added the latest version. Will continue with the future releases. Still a github n00b.

**Comment by moyogo** [comment]
You can either create the tags on github.com or with `git tag` and `git push --tags`.
