### ISSUE TITLE
Kerning problem in Safari with 07.10.2015

### ISSUE THREAD

**Issue by mrflix** [mozilla/Fira#120]
## Chrome
![screen shot 2015-10-08 at 10 58 47](https://cloud.githubusercontent.com/assets/60777/10361969/d366f5c0-6dab-11e5-993f-80dc1f860543.png)
![screen shot 2015-10-08 at 11 00 17](https://cloud.githubusercontent.com/assets/60777/10361993/e883e184-6dab-11e5-888e-3f8c104a7b6e.png)

## Safari
![screen shot 2015-10-08 at 10 52 07](https://cloud.githubusercontent.com/assets/60777/10361860/351ac9d2-6dab-11e5-9e9f-64c469d2188f.png)
![screen shot 2015-10-08 at 10 57 17](https://cloud.githubusercontent.com/assets/60777/10361891/6693089e-6dab-11e5-929d-a1a2a664b7ec.png)

**Comment by patrykdesign** [comment]
@mrflix I think this is more a Google Fonts issue. I see they removed "hair" width from the options list (which is correct) since "hair" is more of an experimental weight.

**Comment by mrflix** [comment]
@patrykdesign I discovered the problem in a user interface of a not yet release project. Thats why I used Google Fonts as an example. In the project I use the font files straight out of this repository and I updated them one month ago. I use the book weight and there the same kerning folding appears.

**Comment by patrykdesign** [comment]
Ok we'll have a look

**Comment by mrflix** [comment]
I can't reproduce the bug so I assume it was a mistake on my side.
http://codepen.io/anon/pen/mVQpzq
