### ISSUE TITLE
Drop local('…') from fira.css

### ISSUE THREAD

**Issue by Schweinepriester** [mozilla/Fira#123]
<http://www.bramstein.com/writing/web-font-anti-patterns-local-fonts.html>

> This “op­ti­mi­sa­tion” is pri­mar­ily used by Google Fonts, but it’s pop­ping up in blogs and ar­ti­cles every now and then. Yes, it will be faster. But it is not a good idea un­less you ac­cept your site may look wildly dif­fer­ent de­pend­ing on what fonts your users have in­stalled. It makes more sense to load a web font and to fall back on sys­tem fonts when the web font is not avail­able, rather than deal with the mul­ti­tude of lo­cally in­stalled ver­sions of a web font. Some op­ti­mi­sa­tions are too good to be true.

**Comment by Schweinepriester** [comment]
@patrykdesign "nice to have" means its accepted? can/should i do a pull request?

**Comment by patrykdesign** [comment]
@Schweinepriester if you can do a pull request, I'll accept it.

**Comment by Schweinepriester** [comment]
@patrykdesign Here we go, see #143 :)
