### ISSUE TITLE
More CDN-Stuff…

### ISSUE THREAD

**Issue by Schweinepriester** [mozilla/Fira#124]
# Immediate
- IPv6?
- HTTP/2?

# Future
- [HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning)?
- When HTTPS-only => [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)?

I know, Amazon S3 atm., therefore bound to what they support, but at least to bring up future stuff I'd like to see sooner than later…

**Comment by patrykdesign** [comment]
@potch for comment / awareness

**Comment by potch** [comment]
The CDN is Amazon S3 and Cloudfront. If/when those services gain these features, we will get them. No plans to change those service providers at the moment.
