### ISSUE TITLE
Figure space

### ISSUE THREAD

**Issue by msdsk** [mozilla/Fira#128]
Figure space is too short; it doesn't match up width of a tabular number, instead it's the same width as a regular space.
Or is it just a problem with ttf version of the font?

**Comment by jfkthame** [comment]
What version of the font are you using, and how did you compare the widths? I just looked at Fira Sans Regular (in both OTF and TTF forms) in v4.105, and AFAICS the figure-space and the tabular numbers share the same width (560 units).

**Comment by msdsk** [comment]
.ttf version 3.111; after some trials it turns out it's a problem with adobe illustrator, as it works in inDesign and in a webfont generated of the same font.
