### ISSUE TITLE
@ returns a musical symbol

### ISSUE THREAD

**Issue by danielsamuels** [mozilla/Fira#133]
First noticed on JSFiddle, but also occurs on Typecast.

Tested in Chrome 47.0.2526.73, Firefox 42, Safari 9.0.2 on Mac OS 10.11.2 Beta.

![](https://i.imgur.com/ETOJUm8.png)

**Comment by patrykdesign** [comment]
@danielsamuels 
Weird I can't seem to replicate this in typecast http://typecast.com/preview/google/Fira%20Mono

**Comment by danielsamuels** [comment]
That's the exact page I used to repro it. If there's any information you would like from me to help track down the problem, just let me know. Happy to help.

**Comment by patrykdesign** [comment]
@danielsamuels do you have the latest Fira fonts installed? I believe sometimes it uses your local copies, but I tried the page on every browser (Firefox, Chrome and Safari) and couldn't replicate.

**Comment by danielsamuels** [comment]
I don't have the fonts installed at all as far as I'm aware, unless they're somehow under another name?

**Comment by patrykdesign** [comment]
@danielsamuels I am not sure what happening, I even tried it out on mobile phones using Chrome and Firefox, couldn't replicate the issue. 
Does it display okay on other websites such as: http://www.fontsquirrel.com/fonts/fira-mono

**Comment by danielsamuels** [comment]
Looks fine on that page:

![](https://i.imgur.com/0afyxZn.png)

**Comment by patrykdesign** [comment]
So it seems to be a problem with Typecast, I'll message them and make sure they update their source files.
