### ISSUE TITLE
Fira Mono Ampersand for Fira Sans

### ISSUE THREAD

**Issue by koesherbacon** [mozilla/Fira#136]
Hello,

I don't really think this would qualify as a true issue but having no other place to post this, I guess this will do.  Anyway, I love the Fira Mono ampersand symbol, it's much more similar to the way I actually write it myself and frankly I simply find it more aesthetically interesting than the standard-looking one of Fira Sans.

Here's some images of what I'm asking about.

The one I really like:
![selection_003](https://cloud.githubusercontent.com/assets/476874/11947566/b63c9a66-a81d-11e5-8318-df95c55cbd37.png)

And the one that's Plain-Jane:
![selection_004](https://cloud.githubusercontent.com/assets/476874/11947567/c0c8cf4a-a81d-11e5-9761-cafb10e94cc4.png)

Thanks!

**Comment by patrykdesign** [comment]
We have a fancy Ampersand in the font already, its just an alternate. We chose to make the standard ampersand more "plain jane" thanks to user feedback after v.1, for legibility purposes we choice one that seemed more recognizable.
