### ISSUE TITLE
Mono font contains "fi" ligature

### ISSUE THREAD

**Issue by tanmatra** [mozilla/Fira#14]
It brokes columns. Apparenlty, ture monospaced font cannot have any ligatures.
![fira mono](https://f.cloud.github.com/assets/708023/1215869/837846ae-2677-11e3-9e0c-b1ba28a78e59.png)

**Comment by danzek** [comment]
This still appears to be an issue when I use this font through Google Fonts.

**Comment by jfkthame** [comment]
That needs to be solved by the Google Fonts service -- they're apparently still using an old version of the font.

@davelab6 might be able to get this fixed?
