### ISSUE TITLE
Italics: Cursor not visible

### ISSUE THREAD

**Issue by weltweitleben** [mozilla/Fira#144]
I try to use Fira Sans Medium Italic and Fira Sans Light Italic with Microsoft Word 2007 (with Win7), but the cursor is not visible unless I zoom into the document (deependig on the view mode at least to 120 oder 130%). This does not happen with other fonts nor with the non-italics. Fira works fine with LibreOffice on Mac aswell.

**Comment by patrykdesign** [comment]
I tried this out on Microsoft Word 2010 (Windows 10) without issue, so clearly they fixed it. Have you tried on newer software, afterall Word 2007 is about 10 years old now!
@weltweitleben

**Comment by weltweitleben** [comment]
Thanks for trying it on Word 2010, @patrykdesign. I couldn't try it on Office 2010, but it worked fine e.g. with LibreOffice. Unfortunately, old MS-Software is still in use in business environment...
