### ISSUE TITLE
CSS being served with an incorrect MIME type.

### ISSUE THREAD

**Issue by bheesham** [mozilla/Fira#145]
`https://code.cdn.mozilla.net/fonts/fira.css` is served with `application/octet-stream` which makes FF43 throw: 

```
The stylesheet https://code.cdn.mozilla.net/fonts/fira.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
```

That results in the css file not being loaded. :sob:

**Comment by potch** [comment]
Is this still occuring? I see text/css when I request it.

**Comment by jfkthame** [comment]
There's something odd/inconsistent going on here..... I tried loading https://code.cdn.mozilla.net/fonts/fira.css (directly in the browser, just pasting that URL into the address bar), and indeed, it was served as text/css and displayed as text in the window. But trying to do that repeatedly, I frequently seem to be getting it as application/octet-stream instead, resulting in a Save File prompt.

**Comment by jfkthame** [comment]
Hmm... if I request it via http (not https), I seem to get text/css every time. But over https, I'm seeing application/octet-stream pretty consistently, although I'm fairly sure I did get text/css at least a couple of times.

**Comment by potch** [comment]
I ran 
```sh
for i in {1..10}; do
  curl -sI http://code.cdn.mozilla.net/fonts/fira.css 2> /dev/null | grep "Content-Type"
done
```

and got
```
Content-Type: application/octet-stream
Content-Type: text/css
Content-Type: text/css
Content-Type: application/octet-stream
Content-Type: application/octet-stream
Content-Type: application/octet-stream
Content-Type: text/css
Content-Type: application/octet-stream
Content-Type: text/css
Content-Type: application/octet-stream
```

This is... not ideal. I've contacted the IT person in charge of configuring this and asked them to look into it.

**Comment by potch** [comment]
good news, 10/10 returning text/css! let me know if you encounter any more issues.

**Comment by bheesham** [comment]
What was the cause of this issue?
