### ISSUE TITLE
Lowercase Y: Bug or feature?

### ISSUE THREAD

**Issue by mheberger** [mozilla/Fira#166]
Serious question. The lowercase y doesn't look right to me, but perhaps this was an intentional design choice? 

![y](https://cloud.githubusercontent.com/assets/15746631/15254140/24bbcef2-18ea-11e6-962c-ab4afe9569ad.png)

**Comment by easyaspi314** [comment]
That was on purpose from what I can tell. It isn't a grotesque font; so it has different styles than, say, Helvetica, Arial, or Roboto.

**Comment by mheberger** [comment]
OK, I see that this peculiar characteristic of the lowercase y is a feature of the font FF Meta, upon which Fira Sans is based. So it is definitely a "feature."
