### ISSUE TITLE
Add documentation about contributing

### ISSUE THREAD

**Issue by gdamjan** [mozilla/Fira#18]
I'd like to add a fix for #17 but couldn't find what the correct procedure for contributing is. What is the original source format I'd have to use? Is it OTF? Is editing with fontforge ok?

**Comment by patrykdesign** [comment]
Hope this helps: https://docs.google.com/document/d/1QfxweGktJEdBvbd94y-5hiyqu32U9-h_ICPVs76Niyw/edit
Also added the link about contribution into our readme.md file on the main repo.
