### ISSUE TITLE
Supported codepages info incomplete in some fonts

### ISSUE THREAD

**Issue by aaaxx** [mozilla/Fira#21]
Fira Sans Bold and Medium are the only ones that have all supported codepages marked (CP-125...0,1,2,3,4,7,8)

Whereas:
Light, Light-Italic,
Regular, Regular-Italic,
Medium-Italic,
and Bold-Italic
all have only CP-125...0,2,4,7 marked in font metadata.

The issue is present in both OTF and TTF versions.

**Comment by patrykdesign** [comment]
I believe this is fixed unless @aaaxx can say otherwise.
