### ISSUE TITLE
Condensed version of Fira Code

### ISSUE THREAD

**Issue by galdor** [mozilla/Fira#217]
Are there plans to release a condensed version of Fira Code ? It is always nice to have more horizontal space when coding :)

**Comment by khawkins98** [comment]
Fira Code is actually a separate project: https://github.com/tonsky/FiraCode

**Comment by galdor** [comment]
Thank you.

**Comment by atheistray** [comment]
Mozilla has abandoned this project, so you won't find any new development here. The good news is the designers of this typeface decided to continue on their own. Check out this repo instead.
https://github.com/bBoxType/FiraGO/blob/master/README.md
