### ISSUE TITLE
Fira font family and reserved font names

### ISSUE THREAD

**Issue by tonsky** [mozilla/Fira#218]
Hi!

Sorry, I couldn’t find any email to contact, trying here.

My name is Nikita, I’m the author of Fira Code font (https://github.com/tonsky/FiraCode), a fork of original Fira Mono that adds ligatures for programming. It’s been around for 3,5 years, seen 17 releases (latest one just 3 weeks ago) and proved to be quite popular (21K+ stars on github). Lots of programmers use it for coding and I see it on slides or screenshots everywhere. As a result of that, people expect to see it on Google Fonts too (see https://github.com/google/fonts/issues/1460#issuecomment-368412420)

Recently Dave Crossland (of Google Fonts) draw my attention that they can’t publish my Fira Code version without written permission from Mozilla/Telefonica to use Reserved Font Name < Fira >.

The situation is tricky: https://github.com/tonsky/FiraCode/issues/573

In short, when I cloned Fira Mono in Nov 2014, only reserved font names were Fira Sans and Fira Mono specifically. 5 months later the Mozilla license was changed to reserve < Fira > name, but my work is based on the Nov 2014 version (I haven’t pulled in any updates since, nor I plan to, as I’m not sure how to merge them on top of the changes I did back then). As I develop my font publicly, full history of this case can be verified by Github dates/commits/releases, details in the issue https://github.com/tonsky/FiraCode/issues/573

I’m writing hoping we can settle this down somehow. As I understand the chain of events, the terms of original license apply, so I’m not in direct conflict with those (am I correct about that?). Still, ideally I’d love to have an official permission to use the name Fira Code (if possible), as it would make all things much easier for me and Dave/Google Fonts can relax about that situation. I’m not making any money from it, it’s just a free font I work on in my spare time (I’m a programmer professionally https://github.com/tonsky, not even a font designer) that lots of people seem to like.

Thanks in advance,
Best regards

Nikita Prokopov
Author of Fira Code

**Comment by Moulick** [comment]
I really hope this goes through. Everyone loves Fira Code

**Comment by potch** [comment]
Hey @tonsky,

I love Fira Code! I have to run this by a few people, but I hope we can unblock you so you can distribute. You can email me at my username AT mozilla.com so any permission is from an official source.

**Comment by potch** [comment]
Hey @tonsky,

I love Fira Code! I have to run this by a few people, but I hope we can unblock you so you can distribute. You can email me at my username AT mozilla.com so any permission is from an official source.

**Comment by potch** [comment]
Bit of a delay here, my apologies.

We're discussing narrowing the RFN or removing it altogether in #221.

**Comment by tonsky** [comment]
Great! Please let me know how it goes

**Comment by takamori** [comment]
Is this resolved, with https://github.com/mozilla/Fira/pull/219 having been merged?
