### ISSUE TITLE
(Demo) Fonts still get downloaded if locally installed

### ISSUE THREAD

**Issue by cvan** [mozilla/Fira#22]
Even though I've installed the [TTF and OTF copies](http://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/) of the Fira Sans fonts, the fonts specified in the CSS `@font-face` at-rules are getting loaded.

This is because the `local` rules should be something like

```css
src: local('Fira Sans'), ...
```

instead of

```css
src: local('Fira Sans Light'), ...
```

Although the [spec](http://www.w3.org/TR/css3-fonts/) says otherwise:

> Just as a @font-face rule specifies the characteristics of a single font within a family, the unique name used with local() specifies a single font, not an entire font family.

We could change the WOFFs, but I'd recommend just fixing the locals:

```css
src: local('Fira Sans Light'),
     local('Fira Sans'), ...
```

**Comment by patrykdesign** [comment]
@carrois is this something that needs to be handled on your side?

**Comment by pivanov** [comment]
Hey @cvan can you check this one http://fira-mozilla.sapp.io/ ? If this one is OK I will create PR. Thanks in advance :)

**Comment by pivanov** [comment]
I think this one was fixed here:
https://github.com/mozilla/Fira/commit/44240b74e25691c2c96ae333a2d30aa6d06556ba#diff-77f0adc0d721cc96ae9090155fdad40aR4
