### ISSUE TITLE
Mono ‘r’ looks like dotless ‘i’ at small sizes

### ISSUE THREAD

**Issue by ruud-v-a** [mozilla/Fira#49]
This is Fira Mono 3.110, rendered at 13px in Firefox 30 on Windows 7 (DirectWrite).

![fira](https://cloud.githubusercontent.com/assets/506953/3496028/41842c9e-05de-11e4-9e00-e48b4a6cd321.png)

I read `.chars()` as `.chais()` the first time I saw that.

**Comment by chreekat** [comment]
I'm glad this glyph has been marked for review. I stared at an r standing by itself in some code for a long while, and eventually my brain decided it was an x. I had to see it again in a different context to find out it was actually an r. :)

**Comment by patrykdesign** [comment]
Fixed in the latest Fira Mono 3.2.

**Comment by ruud-v-a** [comment]
Great!

**Comment by dgutov** [comment]
I liked the previous version. The new update makes the curl more prominent, which is usually okay (even though it makes the letter harder to read if it's followed by `m`), but it also makes the stem thicker, which is a bit problematic, again, at small sizes.

**Comment by Jhonyrod** [comment]
I would propose to drop all the serifs on the r and make it look more in line to other sans-serif fonts.
