### ISSUE TITLE
Font looks drastically different after reinstallation

### ISSUE THREAD

**Issue by Poorchop** [mozilla/Fira#58]
I updated to the latest Fira fonts a few days ago on Windows, and the font looks incredibly different now. I was using FIra Mono pretty much system-wide, and it looks taller, narrower on a per-letter basis, and thinner. The biggest issue is the massive amount of extra spacing between individual lines now. I've included a before and after screenshot:

![font](https://cloud.githubusercontent.com/assets/5256208/4298510/558771d2-3e24-11e4-9391-5623f80b7300.png)

It's worth noting that the left is Fira Mono size 9, and the right is Fira Mono size 8.

Here is what Fira Mono 9 looks like now after updating:

![untitled](https://cloud.githubusercontent.com/assets/5256208/4298518/8d8ab058-3e24-11e4-9f5b-a4797ffd4a25.png)

None of these images have been scaled, so they are all direct comparisons. I'm not sure how much of the line spacing is due to pango rendering in the IRC client that I used for these pictures, but nevertheless, FIra Mono looks drastically different in other applications like PuTTY and Notepad++ after I updated. The OpenType version looks grotesque in WIndows and absolutely nothing like what you see in these pictures, but unfortunately, I can't remember if the previous version I was using was OpenType, and I can't remember what version it was either.

**Comment by patrykdesign** [comment]
We're working to address this, the main issue is really the line height which we're addressing in Mono 3.2 coming soon, tracking in issue #67 , but I am not sure why the rendering is off for you.
