### ISSUE TITLE
Please clear fsType indicating restricted embedding and subsetting

### ISSUE THREAD

**Issue by n7s** [mozilla/Fira#59]
It looks like various font files have an fsType set to restrict embedding and subsetting. (Details on http://partners.adobe.com/public/developer/opentype/index_os2.html#fst). 

I imagine this is not your intent for an open font.  
Can this be cleared, please? Thanks.

**Comment by carrois** [comment]
fsType was "editable".
Will be "installable" in 4.0 release.

**Comment by patrykdesign** [comment]
@n7s can you verify in v.4.004, @carrois and Anja believe it should be fixed now. I'll close this bug unless proven otherwise.
