### ISSUE TITLE
Unicode symbol: Gear (U+2699)

### ISSUE THREAD

**Issue by Bahanix** [mozilla/Fira#61]
Firefox OS has a gear icon that is not included in Fira.

![Gear](https://mozorg.cdn.mozilla.net/media/img/styleguide/products/firefoxos/action-icons/common-settings.png?2013-08)

* Firefox OS icons : https://www.mozilla.org/en-US/styleguide/products/firefox-os/actionicons/#blocks
* Gear (U+2699) : http://www.fileformat.info/info/unicode/char/2699/index.htm

Is it in the scope of Fira?

**Comment by patrykdesign** [comment]
Discussed this internally, and if we add this icon, it will be part of a larger icon addition, so I'll count this as an enhancement for a future update.

**Comment by patrykdesign** [comment]
Since we are working on an emoji font (https://github.com/mozilla/fxemoji) we wouldn't want to have duplication / conflict in the system so we will not include icons in the font.
