### ISSUE TITLE
Toolset to build Fira from sources

### ISSUE THREAD

**Issue by tonsky** [mozilla/Fira#62]
Hi!

I wanted to add couple of ligatures to Fira Mono similar to what [Hasklig does to Source Code Pro](https://github.com/i-tu/Hasklig), for personal use.

I’m trying to build Fira Mono from sources but am completely lost. Can you describe what tools I need and short step-by-step explanation what to run in which order?

I’ve tried:
* opening `Fira Mono-Regular.otf` OTF version in FontLab studio but on save it cannot compile OTF features.
* running `makeotf -f Fira\ Mono-Regular.ufo` from AFDKO but it crashes.

I’m a total newbie with modern font editing and I just want to add couple of glyphs and ligature feature. Can you help me with this? (preferably without buying Glyphs.app which is kinda expensive for 1-time personal usage)

Thanks! (great font btw, use it everyday for code editing & in terminal)

**Comment by patrykdesign** [comment]
Sorry for the late reply, those ligatures look cool, we should have a minor update of fira mono (3.2) soon, so once that is in, lets add your ligatures and see how they work.

I know we use glyphs to build the font, so I am not sure any other way to build the UFO file sorry :(

**Comment by tonsky** [comment]
@patrykdesign cool, thanks!

**Comment by davelab6** [comment]
The UFO sources are nice for interchange, but they aren't the actual sources used by the upstream designers - they use Glyphs and thus the `.glyphs` files are the *real* source format :)

**Comment by tonsky** [comment]
I also noticed that `Clone` → `Open UFO in Glyphs` → `Export OTF...` generates slightly different version of the font than is published in `otf` folder:

![screen shot 2015-03-12 at 17 25 57](https://cloud.githubusercontent.com/assets/285292/6616867/95da792e-c8d4-11e4-80cb-19751773f9c5.png)

(downloaded Fira Mono on the left, exported from UFO on the right)

I agree that `.glyphs` source would be very helpful

**Comment by patrykdesign** [comment]
Apparently we're using a "beta" version of glyphs 2 right now, so the glyph file is not going to work in V1 of the app. But as soon as that standardizes, we'll upload a glyphs version of the source as well... might be a few weeks tho.

**Comment by davelab6** [comment]
I'm curious why you are waiting. The Glyphs 2 beta is publicly available to
anyone with a license to Glyphs, and many other libre fonts have glyphs v2
files published on Github.

**Comment by patrykdesign** [comment]
According to Ralph Glyphs 1 or older versions of Glyphs 2 BETA will completely mess up the files if opened and saved. His team is currently working on adding extended Greek and Cyrillic, so once those are done, I would ideally want to release the glyph files as well.

**Comment by patrykdesign** [comment]
Closing since I added source glyphs files to the repo.
