### ISSUE TITLE
CDN does not have expiry date

### ISSUE THREAD

**Issue by cassidyjames** [mozilla/Fira#63]
We were going to use the Mozilla CDN for Fira on our website, but we're seeing significant page load time hits because it doesn't seem to be cached.

Here's the URL: http://code.cdn.mozilla.net/fonts/fira.css

Checking the headers shows no expiry date.

**Comment by Schweinepriester** [comment]
+1

No comment on this yet? Is there a better place for issues regarding Mozilla CDN?

**Comment by Schweinepriester** [comment]
I'd like to add:

```
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Bold.woff
https://code.cdn.mozilla.net/fonts/woff/FiraSans-ExtraBold.woff
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Hair.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Heavy.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Light.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Medium.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-Regular.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-SemiBold.woff 
https://code.cdn.mozilla.net/fonts/woff/FiraSans-UltraLight.woff
```

Basically `*.woff*`.

Also, ping @patrykdesign & @potch

**Comment by patrykdesign** [comment]
@potch owns CDN, I'll ping me internally.

**Comment by potch** [comment]
Hey there- the credentials were reset for the CDN, and I'll have to go through the process of re-acquiring them. Might be a few days.

**Comment by Schweinepriester** [comment]
Hi there - can you elaborate? :)

Alright, thanks, would be good, saving some bandwith.

(Also relevant for the other CDN issues :))

**Comment by Schweinepriester** [comment]
26 days later… How is it going? :)

**Comment by potch** [comment]
Got my credentials last week (finally)! Working on updating cache headers now.

**Comment by Schweinepriester** [comment]
Hurray! :)
