### ISSUE TITLE
Too much space between f and u

### ISSUE THREAD

**Issue by charakterziffer** [mozilla/Fira#64]
Please check the kerning between f and u. In the version 3.111;PS 003.111;hotconv 1.0.70;makeotf.lib2.5.58329 (all weights as I can see) there are 30 upm added, while between f and n/m no extra space is added. In some text sizes this gives the impression that there’s a space after the f, see attachment.
![fu-lucke](https://cloud.githubusercontent.com/assets/7194876/5237658/38be8360-7894-11e4-96f9-872f1698966d.png)

**Comment by patrykdesign** [comment]
@charakterziffer looks to be fixed in v.4.002. Let me know if you're still seeing the issue.

**Comment by charakterziffer** [comment]
In some weights of Fira Sans v4.003 the letter pair f and u still gets some space by a kerning class (while f+n or f+r doesn’t). As far as I can see this affects only italic versions: Italic (30upm), MediumItalic (20upm), LightItalic (30upm), BoldItalic (11upm), Semi-BoldItalic (16upm), BookItalic (30upm), EightItalic (30), UltraItalic (-7, surprise!), ExtraBoldItalic (6), ExtraLightItalic (30), FourItalic (30), HairItalic (30), ThinItalic (30), TwoItalic (30), UltraLightItalic (30).

Maybe it’s intended? Or the u is just in the wrong kerning class?

**Comment by patrykdesign** [comment]
@carrois I can confirm this is still happening in the italic. See below, the "far" combination is nicely spaced but "fur" seems to have more space around the "u" even though the "u" is narrower than the "a".
![screen shot 2015-03-16 at 4 44 38 pm](https://cloud.githubusercontent.com/assets/1503049/6676125/fd8a676c-cbfb-11e4-90c0-92559fff5e4e.png)

**Comment by patrykdesign** [comment]
@charakterziffer thanks for giving us a more detailed instance. I think in the roman it was fixed in v.4.002, I had trouble replicating it.

**Comment by carrois** [comment]
Sorry. Will be fixed with 4.004!

Am 16.03.2015 um 21:46 schrieb Patryk Adamczyk <notifications@github.com>:

**Comment by patrykdesign** [comment]
Verified in v.4.004, looks to have equal kerning now.
