### ISSUE TITLE
CSS, Greek and Safari

### ISSUE THREAD

**Issue by wfdd** [mozilla/Fira#65]
In Greek, words written in all capitals are not accented.  When using `text-transform: uppercase`, Firefox and Chrome know to use the unaccented glyphs, but Safari doesn't.  In another free front I've used quite extensively, Lato, they're unaccented even in Safari.  I thought Lato might be using a substitution, but it doesn't seem to be that way.  Would anybody here have any ideas?

**Comment by carrois** [comment]
Thanks for reporting.
Obviously Lato uses an additional feature which particularly determines greek caps without accents in all cap use. Like that, it’s sure no matter what the browser or application does automatically.

We’ll address this issue as part of the Greek Extended update within the next months.

**Comment by patrykdesign** [comment]
@wfdd I believe this should be fixed in the new Fira Sans v.4.1 can you please confirm?

**Comment by wfdd** [comment]
Affirm. The kerning also appears to have been improved. Thanks for your work!
