### ISSUE TITLE
Greek tonos on capitals falls outside glyph bounds

### ISSUE THREAD

**Issue by wfdd** [mozilla/Fira#66]
<Έ> and <Ί> seem to be the worst offenders, for the obvious reason. The thicker the font, the worse it is. With `heavy`, it takes up the whole width of the preceding space (see e.g. [here](http://openpatata.eu/bill/oi-peri-tis-thalassias-epistimonikis-erevnas-kanonismoi-tou-2014)).

**Comment by carrois** [comment]
In general they can fall outside the glyph boxes.
The conflict with the preceding space in bolder weights will be eliminated in 4.0 release.

**Comment by patrykdesign** [comment]
Should be fixed in Fira v.4.1.
