### ISSUE TITLE
Dot operator (U+22C5) is thin and not horizontally centered

### ISSUE THREAD

**Issue by chreekat** [mozilla/Fira#68]
...considering it is "preferred to U+00B7 for denotation of multiplication."

Multiplication sign (U+00D7) looks good, though. :)

![image](https://cloud.githubusercontent.com/assets/538538/5814658/caa16482-a085-11e4-99c4-ae129ee74311.png)

**Comment by jfkthame** [comment]
The spacing there doesn't match what I see; could you confirm exactly which font and version you're using, and how your sample image was generated?

**Comment by chreekat** [comment]
Version: Fira 3.111 
Name: Fira Mono Medium 12.

Downloaded from http://www.carrois.com/fira-3-1/#download. Installed into ~/.local/share/fonts with gnome-font-viewer.

The image I included is a screenshot taken of gnome-terminal on Ubuntu 14.04.

I tried to reproduce it in LibreOffice, and you're right, it looks okay there.

LibreOffice (with DejaVu for comparison): 
![image](https://cloud.githubusercontent.com/assets/538538/5816351/f90c9bf0-a096-11e4-8a3a-5d76bdd6896c.png)


For comparison, here is DejaVu in gnome-terminal: 
![image](https://cloud.githubusercontent.com/assets/538538/5816347/e780422e-a096-11e4-8c52-8a3ca7733249.png)

Perhaps I should bring this up with the gnome-terminal project?

**Comment by jfkthame** [comment]
Fira Mono doesn't include U+22C5, so you're getting font fallback - and it looks like gnome-terminal is not picking a fallback that fits the fixed-width spacing very well. (Maybe it's falling back to a non-monospaced font?)

I'm not sure why Fira Mono doesn't include this codepoint, when it's present in Fira Sans; it would be nice if the character repertoires matched across the whole font collection.

**Comment by chreekat** [comment]
Agreed. I'll close this issue. I don't know how to find whether or not a glyph is included, so I would be a poor candidate for opening an issue based on what you described — but I think it should be opened. (nudge, wink)
