### ISSUE TITLE
/lacute in Fira-Hair is wrong

### ISSUE THREAD

**Issue by weiweihuanghuang** [mozilla/Fira#69]
The acute is in the middle of the glyph.

![screen shot 2015-01-27 at 12 03 18 pm](https://cloud.githubusercontent.com/assets/1271897/5917407/81fdfe88-a61c-11e4-9d98-2f0b1c2e9846.png)
Just for illustration, left is /lacute, right is /lslash

**Comment by carrois** [comment]
Will be fixed in 4.0

**Comment by patrykdesign** [comment]
Looks to be fixed in v.4
