### ISSUE TITLE
Please support Latin Extended Additional

### ISSUE THREAD

**Issue by singoc** [mozilla/Fira#71]
Fira is best ever font I've used but sadly it does not support full Unicode chars. I would like to request adding follow char from Latin Extended Additional table. Pls help.
http://www.unicode.org/charts/PDF/U1E00.pdf

**Comment by patrykdesign** [comment]
@singoc should be fixed with the latest update: Fira 4.001

**Comment by singoc** [comment]
Big thanks

**Comment by patrykdesign** [comment]
@singoc we're still adding more glyphs to Latin, more updates coming in the next couple of weeks.
