### ISSUE TITLE
Google Fonts does not contain all weights of this font

### ISSUE THREAD

**Issue by sid-kap** [mozilla/Fira#73]
I noticed that Google Fonts (http://www.google.com/fonts/specimen/Fira+Sans) does not contain all of the weights of Fira Sans, including FiraSans-ExtraLight and FiraSans-UltraLight. 

Are there plans to add these to the Google Fonts repository?

**Comment by patrykdesign** [comment]
Yes we are working with them, its been in their queue to add Fira's extended weights for a while now.
