### ISSUE TITLE
Problem with " glyph in Fira display

### ISSUE THREAD

**Issue by Manuel-K** [mozilla/Fira#77]
I hope this is the right place, but there is something wrong with the " glyph in all weights of Fira except Regular on http://mozilla.github.io/Fira/

The '" of the sample text are overlapping. The " doesn't seem to have the necessary width.

The problem doesn't occur when using the version from the FiraFonts4004.zip archive.

It's nothing major, but I think it's a bad that this happens in a showcase page.

The font version in the gh-pages branch seems to be outdated.

**Comment by patrykdesign** [comment]
Thanks just added a new version of Fira: 4.1, it appears to have fixed the issue.

**Comment by Manuel-K** [comment]
I still see the problem. But you just updated the master branch. The problem will be fixed when you push the new font versions to the gh-pages branch.

Thank you for updating master. I was going to bug you about that, too.

**Comment by Manuel-K** [comment]
Oh. And another thing: the Readme still points to http://www.carrois.com/fira-4-0/ instead of http://www.carrois.com/fira-4-1/

**Comment by patrykdesign** [comment]
@Manuel-K ok I think we're good now.

**Comment by Manuel-K** [comment]
Yes. Thanks.
