### ISSUE TITLE
Fix file permissions

### ISSUE THREAD

**Issue by superlukas** [mozilla/Fira#78]
Fira Mono's OTF files are executable and the license files are as well.

--- edit ---

I just realized Fira Mono's OTF files aren't readable by group and other either. They should probably just be (re)set to 644.

**Comment by patrykdesign** [comment]
Hey @superlukas is there an easy way to change permissions, wouldn't want to do it file by file. Thanks!

**Comment by superlukas** [comment]
@patrykdesign Are you on OS X/Linux or Windows?

**Comment by patrykdesign** [comment]
OS X @superlukas

**Comment by superlukas** [comment]
@patrykdesign Cool, let's roll!

First open up Terminal.app and navigate to the Fira directory like so: `cd ~/Downloads/Fira` (or where ever it might be) and then change the permissions with the following commands:

```sh
# Once for every directory
chmod 644 otf/*.otf
# And the license file
chmod 644 LICENSE
```

I don't recall the exact directory structure but I hope you can take it from here (don't hesitate to ask though). I guess all you really needed was the `chmod 644` part.

**Comment by superlukas** [comment]
@patrykdesign I'm sorry, It looks like somebody has done this already. It's just the files in the zip file you can download from @carrois that have bad file permissions. I assumed they were identical with the ones in this repo, but apparently not.

**Comment by patrykdesign** [comment]
Ok great. We are waiting for a bug fix update, so I'll just make sure when I upload the new files, I'll run them with the permission fix just in case. @superlukas
