### ISSUE TITLE
Missing/incorrect anchor for marks above, on precomposed glyphs including dot or macron below

### ISSUE THREAD

**Issue by jfkthame** [mozilla/Fira#85]
It looks like many (if not all) composites that include the dot-below or macron-below component do not have the proper mark attachment for added diacritics above.

This affects characters such as U+1E63, U+1E5B, U+1E47, and many more.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1167071

**Comment by jfkthame** [comment]
In Fira Sans 4.103, downloaded today, the combinations ẹ́ ẹ̀ ẹ̄ all render OK with the .ttf version of the font, but are still broken in the .otf version. (Note that we use the .otf files on FxOS devices.)

**Comment by patrykdesign** [comment]
Fixed with Fira 4.105
