### ISSUE TITLE
Please change the j back!

### ISSUE THREAD

**Issue by ghost** [mozilla/Fira#89]
The current j, which was changed from Spiekermann's original is just plain wrong.  The vertical stroke of the j should set the center of the glyph (in the same manner as the letter i).  Now there is too much white space to the left side.  Extending serifs left doesn't make up for the imbalance of whitespace there.  Look to any other mono font out there and you'll see this change is a strange anomaly.  Just my 2 cents.

**Comment by patrykdesign** [comment]
@carrois what do you think? It does look a little off, too right focused compared when placed after an "a" or "o".

**Comment by carrois** [comment]
Not wrong, a matter of taste.
We change /j some years ago cause people said the right space is to large.
BTW: ”Spiekermann's original“ was also design by us ;-)

![feura](https://cloud.githubusercontent.com/assets/7803690/9467449/12d94060-4b3c-11e5-9852-e3660f4f4353.png)
![aktuell](https://cloud.githubusercontent.com/assets/7803690/9467448/12d71fba-4b3c-11e5-9310-13190ca39909.png)

**Comment by patrykdesign** [comment]
@ghost as @carrois mentioned, we discussed this internally and yes there is a balance between left and right spacing. We may tweak this a little in the next update, but it will likely stay as is.
