### ISSUE TITLE
Subtle width bug with latest Chrome - adding 0.016px if whitespace after inline/inline-block content

### ISSUE THREAD

**Issue by tim-reynolds** [mozilla/Fira#92]
https://jsfiddle.net/moxr802x/1/

If you go to that and inspect the HTML in the results panel, you will see HTML comments about the tests. There are 10 tests. 

The first 5 have Fira Sans applied as a font-family. The second 5 do not. 

All the HTML is identical between the first and second block of tests. As is the styling, aside from the font-family. 

This is as reduced as a test as I could produce. I am sorry I embedded the images in base64 encoding but I didn't want to hot-link to any of the free image hosting services. 

For all these tests, I expect a width of 400px on the DIV and A tags. 

| Test | Result  | About                                                              |
|------|---------|--------------------------------------------------------------------|
| 1    | 400.016 | Image is on its own line with whitespace before and after          |
| 2    | 400.016 | Image is on the same line as the DIV tag, with one space after.    |
| 3    | 400     | Image is on the same line as the DIV tag, no space after.          |
| 4    | 400.016 | Content block is display:inline-block and has whitespace after     |
| 5    | 400     | Content block is display: inline-block but has no whitespace after |
| 6    | 400     | Same as test 1, no Fira Sans                                       |
| 7    | 400     | Same as test 2, no Fira Sans                                       |
| 8    | 400     | Same as test 3, no Fira Sans                                       |
| 9    | 400     | Same as test 4, no Fira Sans                                       |
| 10   | 400     | Same as test 5, no Fira Sans                                       |

**Comment by Gnodiah** [comment]
@tim-reynolds This is a bug of Chrome, it occurs in the newest version of Chrome([see this](https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=478014)). I believe this problem has been fixed in the current beta release of Chrome.

**Comment by tim-reynolds** [comment]
Thanks for the update. I suspected as much but found it odd that it only happened with your font in my tests. Who knows what triggers it. Just glad it's getting fixed. 

Also thanks for the font. :)
